version: "3.3"
services:
  vault:
    image: vault
    container_name: vault-dev
    ports:
      - '8200:8200'
    restart: always
    volumes:
      - ./vault/config:/vault/config
      - ./vault/policies:/vault/policies
      - ./vault/data:/vault/data
      - ./vault/logs:/vault/logs
    environment:
      VAULT_DEV_ROOT_TOKEN_ID: '00000000-0000-0000-0000-000000000000'

    cap_add:
      - IPC_LOCK
  db:
    image: mysql:oracle
    container_name: mysql-dev
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 'ready2go'
    ports:
      - '3306:3306'
